### ISSUE TITLE
Add moment manipulation functions

### ISSUE THREAD

**Issue by lukerandall** [passy/purescript-simple-moment#1]
Hey, thanks for the useful moment wrapper! We use moment quite a bit in an app we're developing, and would like some functions for manipulating moments (like `startOf`, `endOf`, `add`, `subtract`). Are you open to accepting a PR that adds them? 

I see in the README you say a lot of this is obsolete because of `purescript-datetime`, but I don't see how you're accomplishing the equivalent of the above-mentioned functions with `purescript-datetime`. Maybe you explain how you're using that instead of moment?

**Comment by passy** [comment]
Hey! I'm totally open for any additions to make this library more useful. To be totally frank, I completely forgot about this library.

I felt that with the instances for `Ring`/`Semiring` most of my needs for composing multiple instances was covered, but for `startOf` for example I didn't even know it existed.
